name: Inputs demo

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "skip dev only print build output"
        default: false

      target-environment:
        type: environment
        required: true
        description: "which environment the workflow will target"

      tag:
        type: choice
        options:
          - v1.0
          - v1.1
          - v1.2
        description: "which tag to build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        run: echo "building from tag ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Deploy
        run: echo "deploying to ${{ inputs.target-environment }}"
