name: Deploy html to s3
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY_ACCESS}}
          aws-region: us-west-2
      - name: code static code to s3
        run: | 
          aws s3 sync ./ s3://githyactions-static-website-demo/ \
          --exclude ".*" \
          --include "index.html"
          
